// 이론 메타 — 30개 챕터 (Auto-generated by scripts/build-theory.mjs)
import { THEORY_MD } from './theoryContent';

export const THEORY: any = {
  subjects: [
  {
    "id": "s1",
    "code": "1과목",
    "title": "데이터 모델링의 이해",
    "sections": [
      {
        "id": "s1-1",
        "title": "1-1. 데이터 모델링의 이해",
        "chapters": [
          {
            "id": "c111",
            "num": "1-1-1",
            "title": "데이터 모델의 이해",
            "oneLine": "DB 설계도 · 개념 → 논리 → 물리 3단계"
          },
          {
            "id": "c112",
            "num": "1-1-2",
            "title": "엔터티",
            "oneLine": "정보의 덩어리 · 5대 특징 (업·식·인·속·관)"
          },
          {
            "id": "c113",
            "num": "1-1-3",
            "title": "속성",
            "oneLine": "엔터티의 세부 항목 · 기본/설계/파생"
          },
          {
            "id": "c114",
            "num": "1-1-4",
            "title": "관계",
            "oneLine": "엔터티 간 연결 · 1:1, 1:N, M:N"
          },
          {
            "id": "c115",
            "num": "1-1-5",
            "title": "식별자",
            "oneLine": "행을 구분하는 표식 · 4대 분류, 4대 조건"
          }
        ]
      },
      {
        "id": "s1-2",
        "title": "1-2. 데이터 모델과 SQL",
        "chapters": [
          {
            "id": "c121",
            "num": "1-2-1",
            "title": "정규화",
            "oneLine": "중복 제거 단계 · 1NF → 2NF → 3NF → BCNF"
          },
          {
            "id": "c122",
            "num": "1-2-2",
            "title": "관계와 조인의 이해",
            "oneLine": "관계 = FK = JOIN 의 토대"
          },
          {
            "id": "c123",
            "num": "1-2-3",
            "title": "모델이 표현하는 트랜잭션의 이해",
            "oneLine": "ACID · 관계의 필수성/식별성"
          },
          {
            "id": "c124",
            "num": "1-2-4",
            "title": "Null 속성의 이해",
            "oneLine": "값 없음 · IS NULL 로만 비교"
          },
          {
            "id": "c125",
            "num": "1-2-5",
            "title": "본질식별자 vs 인조식별자",
            "oneLine": "자연 vs 인위 · 장단점 비교"
          }
        ]
      }
    ],
    "chapters": [
      {
        "id": "c111",
        "title": "데이터 모델의 이해",
        "num": "1-1-1",
        "oneLine": "DB 설계도 · 개념 → 논리 → 물리 3단계",
        "sectionTitle": "1-1. 데이터 모델링의 이해",
        "sectionId": "s1-1",
        "detailed": true,
        "sections": [
          "DB 설계도 · 개념 → 논리 → 물리 3단계"
        ]
      },
      {
        "id": "c112",
        "title": "엔터티",
        "num": "1-1-2",
        "oneLine": "정보의 덩어리 · 5대 특징 (업·식·인·속·관)",
        "sectionTitle": "1-1. 데이터 모델링의 이해",
        "sectionId": "s1-1",
        "detailed": true,
        "sections": [
          "정보의 덩어리 · 5대 특징 (업·식·인·속·관)"
        ]
      },
      {
        "id": "c113",
        "title": "속성",
        "num": "1-1-3",
        "oneLine": "엔터티의 세부 항목 · 기본/설계/파생",
        "sectionTitle": "1-1. 데이터 모델링의 이해",
        "sectionId": "s1-1",
        "detailed": true,
        "sections": [
          "엔터티의 세부 항목 · 기본/설계/파생"
        ]
      },
      {
        "id": "c114",
        "title": "관계",
        "num": "1-1-4",
        "oneLine": "엔터티 간 연결 · 1:1, 1:N, M:N",
        "sectionTitle": "1-1. 데이터 모델링의 이해",
        "sectionId": "s1-1",
        "detailed": true,
        "sections": [
          "엔터티 간 연결 · 1:1, 1:N, M:N"
        ]
      },
      {
        "id": "c115",
        "title": "식별자",
        "num": "1-1-5",
        "oneLine": "행을 구분하는 표식 · 4대 분류, 4대 조건",
        "sectionTitle": "1-1. 데이터 모델링의 이해",
        "sectionId": "s1-1",
        "detailed": true,
        "sections": [
          "행을 구분하는 표식 · 4대 분류, 4대 조건"
        ]
      },
      {
        "id": "c121",
        "title": "정규화",
        "num": "1-2-1",
        "oneLine": "중복 제거 단계 · 1NF → 2NF → 3NF → BCNF",
        "sectionTitle": "1-2. 데이터 모델과 SQL",
        "sectionId": "s1-2",
        "detailed": true,
        "sections": [
          "중복 제거 단계 · 1NF → 2NF → 3NF → BCNF"
        ]
      },
      {
        "id": "c122",
        "title": "관계와 조인의 이해",
        "num": "1-2-2",
        "oneLine": "관계 = FK = JOIN 의 토대",
        "sectionTitle": "1-2. 데이터 모델과 SQL",
        "sectionId": "s1-2",
        "detailed": true,
        "sections": [
          "관계 = FK = JOIN 의 토대"
        ]
      },
      {
        "id": "c123",
        "title": "모델이 표현하는 트랜잭션의 이해",
        "num": "1-2-3",
        "oneLine": "ACID · 관계의 필수성/식별성",
        "sectionTitle": "1-2. 데이터 모델과 SQL",
        "sectionId": "s1-2",
        "detailed": true,
        "sections": [
          "ACID · 관계의 필수성/식별성"
        ]
      },
      {
        "id": "c124",
        "title": "Null 속성의 이해",
        "num": "1-2-4",
        "oneLine": "값 없음 · IS NULL 로만 비교",
        "sectionTitle": "1-2. 데이터 모델과 SQL",
        "sectionId": "s1-2",
        "detailed": true,
        "sections": [
          "값 없음 · IS NULL 로만 비교"
        ]
      },
      {
        "id": "c125",
        "title": "본질식별자 vs 인조식별자",
        "num": "1-2-5",
        "oneLine": "자연 vs 인위 · 장단점 비교",
        "sectionTitle": "1-2. 데이터 모델과 SQL",
        "sectionId": "s1-2",
        "detailed": true,
        "sections": [
          "자연 vs 인위 · 장단점 비교"
        ]
      }
    ]
  },
  {
    "id": "s2",
    "code": "2과목",
    "title": "SQL 기본 및 활용",
    "sections": [
      {
        "id": "s2-1",
        "title": "2-1. SQL 기본",
        "chapters": [
          {
            "id": "c211",
            "num": "2-1-1",
            "title": "관계형 데이터베이스 개요",
            "oneLine": "DDL/DML/DCL/TCL 분류"
          },
          {
            "id": "c212",
            "num": "2-1-2",
            "title": "SELECT 문",
            "oneLine": "작성 vs 실행 순서 (FWGHSO)"
          },
          {
            "id": "c213",
            "num": "2-1-3",
            "title": "함수",
            "oneLine": "단일행/문자/숫자/날짜/변환/NULL"
          },
          {
            "id": "c214",
            "num": "2-1-4",
            "title": "WHERE 절",
            "oneLine": "행 필터 · AND/OR 우선순위"
          },
          {
            "id": "c215",
            "num": "2-1-5",
            "title": "GROUP BY · HAVING 절",
            "oneLine": "그룹화 · WHERE vs HAVING"
          },
          {
            "id": "c216",
            "num": "2-1-6",
            "title": "ORDER BY 절",
            "oneLine": "정렬 · ASC 기본, NULL 위치"
          },
          {
            "id": "c217",
            "num": "2-1-7",
            "title": "조인",
            "oneLine": "EQUI/Non-EQUI/SELF/OUTER/CROSS"
          },
          {
            "id": "c218",
            "num": "2-1-8",
            "title": "표준 조인",
            "oneLine": "INNER/OUTER/CROSS/NATURAL/USING"
          }
        ]
      },
      {
        "id": "s2-2",
        "title": "2-2. SQL 활용",
        "chapters": [
          {
            "id": "c221",
            "num": "2-2-1",
            "title": "서브쿼리",
            "oneLine": "단일행/다중행/연관 · 스칼라/인라인뷰"
          },
          {
            "id": "c222",
            "num": "2-2-2",
            "title": "집합 연산자",
            "oneLine": "UNION / UNION ALL / INTERSECT / MINUS"
          },
          {
            "id": "c223",
            "num": "2-2-3",
            "title": "그룹 함수",
            "oneLine": "ROLLUP / CUBE / GROUPING SETS"
          },
          {
            "id": "c224",
            "num": "2-2-4",
            "title": "윈도우 함수",
            "oneLine": "RANK / ROW_NUMBER / LAG / LEAD"
          },
          {
            "id": "c225",
            "num": "2-2-5",
            "title": "Top N 쿼리",
            "oneLine": "ROWNUM / FETCH FIRST / TOP"
          },
          {
            "id": "c226",
            "num": "2-2-6",
            "title": "계층형 질의와 셀프 조인",
            "oneLine": "CONNECT BY · SELF JOIN"
          },
          {
            "id": "c227",
            "num": "2-2-7",
            "title": "PIVOT / UNPIVOT 절",
            "oneLine": "세로 ↔ 가로 변환"
          },
          {
            "id": "c228",
            "num": "2-2-8",
            "title": "정규 표현식",
            "oneLine": "REGEXP_LIKE / REPLACE / SUBSTR"
          }
        ]
      },
      {
        "id": "s2-3",
        "title": "2-3. 관리 구문",
        "chapters": [
          {
            "id": "c231",
            "num": "2-3-1",
            "title": "DML",
            "oneLine": "INSERT / UPDATE / DELETE / MERGE"
          },
          {
            "id": "c232",
            "num": "2-3-2",
            "title": "TCL",
            "oneLine": "COMMIT / ROLLBACK / SAVEPOINT"
          },
          {
            "id": "c233",
            "num": "2-3-3",
            "title": "DDL",
            "oneLine": "CREATE / ALTER / DROP / TRUNCATE / 제약조건"
          },
          {
            "id": "c234",
            "num": "2-3-4",
            "title": "DCL",
            "oneLine": "GRANT / REVOKE / ROLE"
          }
        ]
      }
    ],
    "chapters": [
      {
        "id": "c211",
        "title": "관계형 데이터베이스 개요",
        "num": "2-1-1",
        "oneLine": "DDL/DML/DCL/TCL 분류",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "DDL/DML/DCL/TCL 분류"
        ]
      },
      {
        "id": "c212",
        "title": "SELECT 문",
        "num": "2-1-2",
        "oneLine": "작성 vs 실행 순서 (FWGHSO)",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "작성 vs 실행 순서 (FWGHSO)"
        ]
      },
      {
        "id": "c213",
        "title": "함수",
        "num": "2-1-3",
        "oneLine": "단일행/문자/숫자/날짜/변환/NULL",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "단일행/문자/숫자/날짜/변환/NULL"
        ]
      },
      {
        "id": "c214",
        "title": "WHERE 절",
        "num": "2-1-4",
        "oneLine": "행 필터 · AND/OR 우선순위",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "행 필터 · AND/OR 우선순위"
        ]
      },
      {
        "id": "c215",
        "title": "GROUP BY · HAVING 절",
        "num": "2-1-5",
        "oneLine": "그룹화 · WHERE vs HAVING",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "그룹화 · WHERE vs HAVING"
        ]
      },
      {
        "id": "c216",
        "title": "ORDER BY 절",
        "num": "2-1-6",
        "oneLine": "정렬 · ASC 기본, NULL 위치",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "정렬 · ASC 기본, NULL 위치"
        ]
      },
      {
        "id": "c217",
        "title": "조인",
        "num": "2-1-7",
        "oneLine": "EQUI/Non-EQUI/SELF/OUTER/CROSS",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "EQUI/Non-EQUI/SELF/OUTER/CROSS"
        ]
      },
      {
        "id": "c218",
        "title": "표준 조인",
        "num": "2-1-8",
        "oneLine": "INNER/OUTER/CROSS/NATURAL/USING",
        "sectionTitle": "2-1. SQL 기본",
        "sectionId": "s2-1",
        "detailed": true,
        "sections": [
          "INNER/OUTER/CROSS/NATURAL/USING"
        ]
      },
      {
        "id": "c221",
        "title": "서브쿼리",
        "num": "2-2-1",
        "oneLine": "단일행/다중행/연관 · 스칼라/인라인뷰",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "단일행/다중행/연관 · 스칼라/인라인뷰"
        ]
      },
      {
        "id": "c222",
        "title": "집합 연산자",
        "num": "2-2-2",
        "oneLine": "UNION / UNION ALL / INTERSECT / MINUS",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "UNION / UNION ALL / INTERSECT / MINUS"
        ]
      },
      {
        "id": "c223",
        "title": "그룹 함수",
        "num": "2-2-3",
        "oneLine": "ROLLUP / CUBE / GROUPING SETS",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "ROLLUP / CUBE / GROUPING SETS"
        ]
      },
      {
        "id": "c224",
        "title": "윈도우 함수",
        "num": "2-2-4",
        "oneLine": "RANK / ROW_NUMBER / LAG / LEAD",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "RANK / ROW_NUMBER / LAG / LEAD"
        ]
      },
      {
        "id": "c225",
        "title": "Top N 쿼리",
        "num": "2-2-5",
        "oneLine": "ROWNUM / FETCH FIRST / TOP",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "ROWNUM / FETCH FIRST / TOP"
        ]
      },
      {
        "id": "c226",
        "title": "계층형 질의와 셀프 조인",
        "num": "2-2-6",
        "oneLine": "CONNECT BY · SELF JOIN",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "CONNECT BY · SELF JOIN"
        ]
      },
      {
        "id": "c227",
        "title": "PIVOT / UNPIVOT 절",
        "num": "2-2-7",
        "oneLine": "세로 ↔ 가로 변환",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "세로 ↔ 가로 변환"
        ]
      },
      {
        "id": "c228",
        "title": "정규 표현식",
        "num": "2-2-8",
        "oneLine": "REGEXP_LIKE / REPLACE / SUBSTR",
        "sectionTitle": "2-2. SQL 활용",
        "sectionId": "s2-2",
        "detailed": true,
        "sections": [
          "REGEXP_LIKE / REPLACE / SUBSTR"
        ]
      },
      {
        "id": "c231",
        "title": "DML",
        "num": "2-3-1",
        "oneLine": "INSERT / UPDATE / DELETE / MERGE",
        "sectionTitle": "2-3. 관리 구문",
        "sectionId": "s2-3",
        "detailed": true,
        "sections": [
          "INSERT / UPDATE / DELETE / MERGE"
        ]
      },
      {
        "id": "c232",
        "title": "TCL",
        "num": "2-3-2",
        "oneLine": "COMMIT / ROLLBACK / SAVEPOINT",
        "sectionTitle": "2-3. 관리 구문",
        "sectionId": "s2-3",
        "detailed": true,
        "sections": [
          "COMMIT / ROLLBACK / SAVEPOINT"
        ]
      },
      {
        "id": "c233",
        "title": "DDL",
        "num": "2-3-3",
        "oneLine": "CREATE / ALTER / DROP / TRUNCATE / 제약조건",
        "sectionTitle": "2-3. 관리 구문",
        "sectionId": "s2-3",
        "detailed": true,
        "sections": [
          "CREATE / ALTER / DROP / TRUNCATE / 제약조건"
        ]
      },
      {
        "id": "c234",
        "title": "DCL",
        "num": "2-3-4",
        "oneLine": "GRANT / REVOKE / ROLE",
        "sectionTitle": "2-3. 관리 구문",
        "sectionId": "s2-3",
        "detailed": true,
        "sections": [
          "GRANT / REVOKE / ROLE"
        ]
      }
    ]
  }
],
};

export const THEORY_BODY: any = THEORY_MD;
